[build]
  command = "npm run netlify-build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "netlify"

[functions]
  directory = ".netlify/functions-internal"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 